name: Featurebranch
on:
  push:
    branches-ignore:
      - 'master'
      - 'develop'
      - '*android*'

jobs:
  # ==========================================================================
  # Build all x86 Linux flavours
  buildLinux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ CentOS/Dockerfile, Debian/Dockerfile_Buster, Debian/Dockerfile_Stretch, Fedora/Dockerfile, OpenSUSE/Dockerfile, Ubuntu/Dockerfile_18_04, Ubuntu/Dockerfile_20_04 ]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build binaries
        run: docker build -t local -f Docker/${{ matrix.distro }}_noUpload --build-arg BUILD_THREADS=2 .
        env:
          GITHUB_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ==========================================================================
  # Build aarch64 version (Raspberry PI ARMv8)
  buildARM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
      - name: Build binaries
        run: docker build -t local -f Docker/RaspberryPi/Dockerfile_Buster_noUpload --build-arg BUILD_THREADS=2 .
        env:
          GITHUB_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ==========================================================================
  # Build MacOS version
  buildMacOS:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.5.1'

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.10'
          modules: 'qtwebengine'

      - name: Install dependencies
        run: |
          brew uninstall --ignore-dependencies berkeley-db
          brew install berkeley-db@4 boost openssl

      - name: Cache build dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-build-dependencies-mac-v3
        with:
          path: |
            ${{ github.workspace }}/cmake-build-cmdline-mac/*
            !${{ github.workspace }}/cmake-build-cmdline-mac/aliaswallet
            ~/Archives/Tor/Tor.libraries.MacOS.zip
          key: ${{ runner.os }}-${{ env.cache-name }}

      - name: Build MacOS binaries
        run: ./scripts/cmake-build-mac.sh -g
        env:
          MAC_QT_DIR: ${{ env.Qt5_DIR }}

  # ==========================================================================
  # Build Windows x64 version
  buildWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.9'
          setup-python: 'false'
          modules: 'qtwebengine'

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          vcpkgArguments: berkeleydb:x64-windows boost:x64-windows leveldb:x64-windows openssl:x64-windows
          vcpkgTriplet: x64-windows
          vcpkgDirectory: 'C:\vcpkg'
          vcpkgGitCommitId: aa028e94d733b03852ea441b2474468f43d94c5b

      - name: Build Windows binaries
        run: ./scripts/cmake-build-win.bat
        env:
          VCPKG_DEFAULT_TRIPLET: x64-windows
          QTDIR: ${{ env.Qt5_Dir }}
          VSDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise'
          CMAKEDIR: 'C:\Program Files\CMake\bin'
          VCPKGDIR: 'C:\vcpkg'

  # ==========================================================================
  # Build Windows x86 version
  buildWindowsX86:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.9'
          setup-python: 'false'
          modules: 'qtwebengine'
          arch: 'win32_msvc2017'

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          vcpkgArguments: berkeleydb:x86-windows boost:x86-windows leveldb:x86-windows openssl:x86-windows
          vcpkgTriplet: x86-windows
          vcpkgDirectory: 'C:\vcpkg'
          vcpkgGitCommitId: aa028e94d733b03852ea441b2474468f43d94c5b

      - name: Build Windows binaries
        run: ./scripts/cmake-build-win-x86.bat
        env:
          VCPKG_DEFAULT_TRIPLET: x86-windows
          QTDIR_x86: ${{ env.Qt5_Dir }}
          VSDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise'
          CMAKEDIR_x86: 'C:\Program Files\CMake\bin'
          VCPKGDIR: 'C:\vcpkg'
